### ISSUE TITLE
lazy_streams not working with python3

### ISSUE THREAD

**Issue by PiotrMaciejKowalski** [brettschneider/python_lazy_streams#1]
Hi brettschneider,
Currently your code doesn't work with python 3 (3.7 in my case). Yet this could actually be fixed quite easily, as I did the required changes locally. 

1. In python3 reduce is not provide by builtins. 'from functools import reduce' should be added in the case
1. In python3 xrange is replaced by range
1. In promise_keeper  'from Queue import Queue, Empty' should be replaced by 'from queue import Queue, Empty'

Having this code working in both python2 and 3, one can use the following trick:
https://stackoverflow.com/questions/29687837/queue-importerror-in-python-3/29688081#29688081
Kind regards,
Piotr Kowalski

**Comment by RemiDesgrange** [comment]
I @brettschneider would you be interested in a PR to make it work with python3 (and drop python2 since deprecated ??)

**Comment by brettschneider** [comment]
Sure

**Comment by RemiDesgrange** [comment]
I'll do a proper PR in promise-keeper first. And then here

**Comment by eeriksp** [comment]
Hi!
Are there any updates on this issue?

**Comment by RemiDesgrange** [comment]
I started a fork. test are passing. I should submit a PR, but I added type hinting and it's not yet finished.

**Comment by RemiDesgrange** [comment]
https://github.com/brettschneider/python_promise_keeper/pull/1 ok it has been merged and uploaded to pypi. Thanks @brettschneider  !! I'll do a proper PR on lazystream soon. And also correct the doc in promise keeper to update the readme !!

**Comment by buiphonght** [comment]
Hi guys. I cannot install the version 0.5. It seems like the latest version on `https://pypi.org/project/lazy-streams/` is 0.4. Could anyone please help me with this?

**Comment by RemiDesgrange** [comment]
there is no 0.5 version

**Comment by buiphonght** [comment]
> [brettschneider/python_promise_keeper#1](https://github.com/brettschneider/python_promise_keeper/pull/1) ok it has been merged and uploaded to pypi. Thanks @brettschneider !! I'll do a proper PR on lazystream soon. And also correct the doc in promise keeper to update the readme !!

Oops! You guys are talking about promise-keeper. I misunderstood that version 0.5 was uploaded to pypi. Really sorry about that. Hope you guys will push version 0.5 to pypi soon. I'm really looking forward to your release. Thank you guys for doing such a great job

**Comment by buiphonght** [comment]
> There is no 0.5 version. 0.5 will be the version once my PR is merged. It's a big one :-)
> 
> In the meantime, you can still use this in your requirements:
> 
> ```
> pip install  git+https://github.com/RemiDesgrange/python_lazy_streams.get@152f87060b6555d8cc7378e5de4097c31d824618
> ```
> 
> didn't test it but something like that

Great. Thank you!

**Comment by brettschneider** [comment]
I know I've been derelict with this project, but I finally got around to releasing the latest code to prod.  It's not functionally any different, just new unit test structure, coverage reporting and some ci/cd.   Releasing future versions should be a lot simpler.
